### ISSUE TITLE
Remove Babel runtime

### ISSUE THREAD

**Issue by dthree** [dthree/vorpal#109]
@scotthovestadt would like to discuss this with you, simply because the `babel-polyfill` and `babel-runtime` modules which are now required for Vorpal take up 2.89MB on a raw download. A few useful shims to me is not worth this.

One of the most important aspects to Vorpal to me is the size. I want it to be a lightweight plug into an app, and right now it makes any app monolithic (adds 5.5MB).

[I am also seeing if I can eliminate `lodash` in the near future as well as it is 1MB in itself. Unfortunately Inquirer.js also depends on this, but if I can handle this, it would bring Vorpal to 844kb.](https://github.com/SBoudrias/Inquirer.js/pull/335)

As a comparison, 

- `yargs` is 1.15MB
- `minimist` is 30.4KB
- `commander` is 46.1KB

Do you see where I'm coming from? Size is pretty important to me. I'm additionally releasing [Cash](https://github.com/vorpaljs/cash) on Monday, and I advertise right off how small it is, when Vorpal is making it huge.

What do you think we can do? Thanks.

**Comment by ristomatti** [comment]
@dthree would it make sense to use `babel-cli` and do with the syntax it can compile without the use of polyfills? The babel modules would be just `devDependencies` in `package.json`. The `.npmignore` file could be configured so that only the module root and the `dist` directory would be included in the NPM package.

James Nelson has written a nice example of that kind of configuration in his post [Writing NPM packages with ES6 using the Babel 6 CLI](http://jamesknelson.com/writing-npm-packages-with-es6-using-the-babel-6-cli/).

**Comment by dthree** [comment]
@ristomatti that's what I have normally been doing, however apparently in order to use some shims in Babel 6, it requires a polyfill lib in the devs. This may be incorrect, I just don't know enough about Babel to give a correct answer at this time, and @scotthovestadt seemed to think this was the case, at least for a bit.

**Comment by ristomatti** [comment]
@dthree yes so it seems. Promises seem to require that. Since Promises are something that really make a big impact on the code readability but seem to be pretty standard in API, maybe some module providing only Promise support could be smaller in size?

Small app size is definately a good thing but I would at least pause for a moment to think if it really is something to worry about in this case unless Vorpal is also used for web development(?). It's worth noting that Node itself is a huge size overhead.

Node is definately popular in environments with little resources but I would argue resources typically being more constrained on CPU, memory and bandwidth than storage. In an environment with very little storage, a compiled binary or a traditional shell script would probably be a more likely choice and a better fit than anything built on top of Node.

**Comment by scotthovestadt** [comment]
I agree with the point @ristomatti made that space isn't an issue in a NodeJS environment. Certainly 1-2MB is not something I worry about.

I think if you like what we can probably do is remove babel-runtime and keep babel-polyfill. babel-polyfill is preferred, but [this](http://www.2ality.com/2015/12/babel6-helpersstandard-library.html#babel-plugin-transform-runtime) issue keeps it from being effective, so I think unless it'll be fixed soon we just drop the runtime and it'll cut the deps in half.

**Comment by dthree** [comment]
Or we could drop support for `.10 - .12`... :)

**Comment by dthree** [comment]
I'm actually thinking about it. I guess we'd have to bump to 2.0 if we drop support for those, but it would be nice.

Do you have any idea what percentage of companies use those older versions?

**Comment by scotthovestadt** [comment]
I honestly think that basically everyone using node would rather have an
extra dependency than worry about having a specific node version.

I think we can drop babel-runtime and use only babel-polyfill for the
immediate future, until the runtime lib is more mature.

**Comment by dthree** [comment]
Okay let's do that then - just drop the babel runtime.

**Comment by dthree** [comment]
@scotthovestadt you think you can help with this in the near future? Thanks.

**Comment by scotthovestadt** [comment]
Yeah. I'll look at it tomorrow. There was a Babel update today and I also
want to go through change log.

**Comment by dthree** [comment]
Awesome! I'm on a roll right now, closed almost 15 issues today so far. Would like to zero out soon.

**Comment by scotthovestadt** [comment]
Done.
