### ISSUE TITLE
unable to locate local storage object in most immediate instance

### ISSUE THREAD

**Issue by GranularDetective** [dthree/vorpal#123]
I don't appear to have a local storage object at all at the moment. Does absence of a local storage object indicate a problem with the install on my current machine?

**Comment by dthree** [comment]
You might not see it, but is the functionality not working?

**Comment by GranularDetective** [comment]
Why doesn't the object show in my development panel? :'(

**Comment by dthree** [comment]
? Vorpal doesn't have a development panel. Are you just trolling? Honestly not a single comment you've made has made any sense to me. 

I'm really trying not to be rude, but please take care to explain your issues better if you're going to post here.

**Comment by GranularDetective** [comment]
Chrome has a development panel and if you look at it the local storage object should be there when doing Web Development.

Sent from Yahoo Mail on Android 
 
  On Tue, 1 Mar, 2016 at 22:48, dc<notifications@github.com> wrote:   
? Vorpal doesn't have a development panel. Are you just trolling? Honestly not a single comment you've made has made any sense to me. 

I'm really trying not to be rude, but please take care to explain your issues better if you're going to post here.

**Comment by dthree** [comment]
Vorpal is a terminal-based software and doesn't work in a browser.

**Comment by Shakyamuni177te** [comment]
I think what she's attempting to tell you is she's looking for the local
storage object in the browser as Vorpal doesn't have a method of finding
the local storage object you are storing at the moment?

**Comment by dthree** [comment]
Yeah, you aren't going to be able to find it in a browser at all.

**Comment by jwthomp** [comment]
@GranularDetective  The local storage data is stored on disk at os.tmpdir() + /.local_storage_<local storage id>

As an example, on Linux if you do vorpal.localStorage('foo'); you can find the directory that contains all data that has been set at /tmp/.local_storage_foo/

**Comment by PeterDCarter** [comment]
My personal feeling, on reflection, is that the user was talking both metaphorically, and in terms of computer code. Perhaps her light-hearted tone regarding her 'local storage object' (I would reference the famous Boxxy Babee video at this point e.g. "This one guy he remixed all of my videos" line) was a sort of cover in order to broach the subject of one person's memories, of a particular emotional and traumatic event, for example, being replaced with other memories via similar but also different means.

Perhaps the user 'GranularDetective' was using the Browser as a metaphor, and she personally wishes to be able to dynamically alter what she would refer to as her 'local storage object'. A subject which she has perhaps spend much thought on in the past, but about which she now feels better and more able to emotionally compartmentalise in a way that is psychologically useful for her.

Though I'm sure she did want to know where the local storage object was stored in Vorpal.js as well. I'm certain that when people write in code they are pretty much always talking about themselves as well...
