### ISSUE TITLE
Align error-message in code with the documentation

### ISSUE THREAD

**Issue by alessandrousseglioviretta** [dthree/vorpal#73]
An error message related to the correct command argument sequence does not reflect the documentation: "Put the required arguments first, and variadic in the back.". (See also gitter chat on Dec 29, 2015, 18:36 CET).

Thanks!

**Comment by dthree** [comment]
That Gitter chat is going to get lost very soon:

---

## Alessando:

Hi! I just started playing around with Vorpal and I have a question. I tried the very first demo command: vorpal .command('foo <requiredArg> [optionalArg]') .option('-v, --verbose', 'Print foobar instead.') ...
the help says: Usage: foo2 [options] <requiredArg> [optionalArg]
but the option must follow the required argument, it cannot precede it
am I missing anything or is the help wrong?
thanks!
here is the error message:

```bash
myapp$ foo --verbose abc

  Missing required argument. Showing Help:
```
this issue also affects the result of appending '--help': foo --help displays an error message instead of the help, because the required argument is missing

---

## DC:

Hey there.
The docs say to do required first:

```
Multiple arguments

Put the required arguments first, and variadic in the back.
```

So that's a bug in the code that the help shows the reverse.
Could you file an issue for me? Thanks!

https://github.com/dthree/vorpal/wiki/api-|-vorpal.command#multiple-arguments

**Comment by dthree** [comment]
Fixed.
